- Projects:
    - Next.js (Frontend):
        icon: react       # ← built-in icon name, no “.png” needed
        href: http://localhost:3000
        description: Frontend server (Next.js)
        ping: http://localhost:3000

    - NestJS (Backend):
        icon: nodejs
        href: http://localhost:4000
        description: Backend API (NestJS)
        ping: http://localhost:4000/health

- Dev Tools:
    - Prisma Studio:
        icon: database
        href: http://localhost:5555
        description: Prisma DB browser (`npx prisma studio`)
    - Swagger API Docs:
        icon: book
        href: http://localhost:4000/api-docs
        description: NestJS Swagger docs
    - Supabase Studio:
        icon: supabase
        href: http://localhost:54323
        description: Supabase local dev tools
    - pgAdmin:
        icon: database
        href: http://localhost:5050
        description: pgAdmin UI
